# configs/hello_world.yaml
#
# Это тестовый конфиг для проверки того, что весь пайплайн (train.py)
# работает правильно, от загрузки конфига до запуска цикла обучения.

general:
  experiment_name: "hello_world_test"
  seed: 42

data:
  is_dummy: true

  # Остальные пути теперь действительно просто плейсхолдеры
  path: "data/dummy/"
  train_file: "dummy_train.csv"
  
  fold_strategy: "StratifiedKFold"
  group_col: "group_id"
  n_splits: 2

model:
  name: "dummy_model"
  pretrained: false
  embedding_size: 512

train_params:
  epochs: 1
  batch_size: 4
  learning_rate: 0.001